[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.pyright]
include = ["src", "tests"]
extraPaths = ["."]

[tool.ruff]
src = ["src", "tests"]

[tool.coverage.run]
source = ["src"]

[tool.coverage.report]
fail_under = 99.5
show_missing = true

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "pylint>=3.3",
  "astroid>=3.3",
  "PyYAML>=6.0",
]
